FROM golang:1.20-alpine AS build 
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . . 
RUN go build -tags netgo -ldflags '-s -w' -o main

FROM alpine:latest
WORKDIR /app 
COPY --from=build /app/main .
ENV API_GATEWAY_PORT=${API_GATEWAY_PORT}
ENV API_ACCESS_KEY=${API_ACCESS_KEY}
ENV STORAGE_SERVICE_PORT=${STORAGE_SERVICE_PORT}
ENV AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
ENV DOCUMENT_SERVICE_PORT=${DOCUMENT_SERVICE_PORT}
ENV MONGO_URI=${MONGO_URI}
ENV OCR_SERVICE_PORT=${OCR_SERVICE_PORT}
ENV BLOCKCHAIN_SERVICE_PORT=${BLOCKCHAIN_SERVICE_PORT}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_NAME=${DB_NAME}
ENV CONSUL_ADDR=${CONSUL_ADDR}
CMD [ "./main"]