global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
scrape_configs:
  - job_name: 'http_request_duration_seconds'
    static_configs:
      - targets: ['landate-gateway:8000']