global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
scrape_configs:
  - job_name: 'http_request_duration_seconds'
    static_configs:
      - targets: ['127.0.0.1:2222', '127.0.0.1:8000']