apiVersion: apps/v1
kind: Deployment
metadata:
  name: landate-api 
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: landate-api 
  template:
    metadata:
      labels:
        app: landate-api 
    spec:
      volumeClaimTemplates:
      - metadata:
          name: landate-pvc 
        spec: 
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
      containers:
        - name: landate-backend
          image: siddhantprateek/landate-backend
          ports:  
            - containerPort: 8000
          resources:
            request:
              cpu: "400m"
              memory: "512Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
        - name: db 
          image: mongo:latest 
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: landate-pvc 
            mountPath: /data/db 
          resources:
            request:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
        - name: postgres 
          image: postgres:13-alpine 
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: landate-pvc 
            mountPath: /var/lib/postgresql/data
          resources:
            request:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
        

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: landate-pvc 
  labels:
    app: landate-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
