version: '3.4'

services:
  apigateway:
    image: polyway
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"

  grafana:
    image: grafana/grafana:latest 
    container_name: grafana 
    ports:
      - "4040:4040"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_BASIC_ENABLED=false 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    networks:
      - monitoring 
    restart: unless-stopped

networks:
  monitoring:

volumes:
  grafana_data:
  prometheus_data: